version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rapidride
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: rapidride_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: .
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:

